---
- name: Current OS version information
  debug:
    var: os_info
  vars:
    os_info:
      distribution: "{{ ansible_distribution }}"
      distribution_major_version: "{{ ansible_distribution_major_version }}"
      distribution_release: "{{ ansible_distribution_release }}"
      distribution_version: "{{ ansible_distribution_version }}"

- name: Ensure deltarpm installed
  yum: name=deltarpm state=latest

- name: Update packages
  yum: name=* state=latest update_cache=yes

- name: Gather facts after upgrade
  setup:
    filter: ansible_distribution*

- name: OS version information after Upgrade
  debug: var=os_info_post_upgrade
  vars:
    os_info_post_upgrade:
      distribution: "{{ ansible_distribution }}"
      distribution_major_version: "{{ ansible_distribution_major_version }}"
      distribution_release: "{{ ansible_distribution_release }}"
      distribution_version: "{{ ansible_distribution_version }}"