---
rest_url: "{{ lookup('env', 'VMWARE_HOST') | default('localhost') }}"
rest_username: "{{ lookup('env', 'VMWARE_USER') }}"
rest_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"

demo_users:
  - username: demouser2
    password: demo
    first_name: demo
    last_name: user2
    email: demouser2@example.com
