- hosts: localhost
  become: no
  tasks:
    - name: Get record for router ELB DNS Entry
      route53:
        command: get
        zone: "{{ hosted_zone_domain_name }}"
        record: "{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
        type: A
      register: routerelbrec
      when: hosted_zone_domain_name is defined and ec2_name_prefix is defined

    - name: Create Router ELB DNS Entry if it doesn't exist
      route53:
        #state: present ## Added in Ansible 2.4 will remove need for when statement below
        command: create
        zone: "{{ hosted_zone_domain_name }}"
        record: "{{ item.invocation.module_args.instance_tags.role | lower }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
        type: A
        value: "{{ item.tagged_instances[0].public_ip }}"
      with_items: "{{ instances.results }}"with_items:
      when: "{} == routerelbrec.set"
