- hosts: localhost
  become: no
  vars_files:
    - nginx-nodes-gce.yml
  pre_tasks:
    - name: print env variables
      shell: printenv
      register: print_env

    - debug:
        var: print_env.stdout

    - name: get pem file
      shell: cat $GCE_PEM_FILE_PATH
      register: pem_file

    - debug:
        var: pem_file.stdout

  #roles:
  #  - ansible-role-gce