- hosts: localhost
  become: no
  tasks:
    - debug:
        var: instances.results[0]

    - name: Get record for router ELB DNS Entry
      route53:
        command: get
        zone: "{{ hosted_zone_domain_name }}"
        record: "{{ subdomain | default(instances.results[0].invocation.module_args.instance_tags.role | lower) }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
        type: A
      register: routerelbrec
      when: hosted_zone_domain_name is defined and ec2_name_prefix is defined

    - name: Create Router ELB DNS Entry if it doesn't exist
      route53:
        #state: present ## Added in Ansible 2.4 will remove need for when statement below
        command: create
        overwrite: yes
        zone: "{{ hosted_zone_domain_name }}"
        record: "{{ subdomain | default(instances.results[0].invocation.module_args.instance_tags.role | lower) }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
        type: A
        value: "{{ instances.results[0].instances[0].public_ip_address }}"
      when: routerelbrec.set is defined and "{} == routerelbrec.set"

    - name: output url
      debug:
        msg: 'application is available at https://{{ subdomain | default(instances.results[0].invocation.module_args.instance_tags.role | lower) }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}/'