- include: nginx_infra_ec2.yml

- hosts: localhost
  become: no
  tasks:
    - name: Add hosts to groups
      add_host:
        name: "{{ item.tagged_instances[0].public_ip }}"
        ansible_host: "{{ item.tagged_instances[0].public_ip }}"
        groups: tag_role_nginx,tag_app_nginx_standalone
      with_items: "{{ instances.results }}"
      when: ('nginx_standalone' in item.invocation.module_args.instance_tags.app) and ('nginx' in item.invocation.module_args.instance_tags.role)
      changed_when: no
      tags:
        - addhost

- include: provision_nginx.yml

- include: nginx_domain.yml
