- hosts: localhost
  become: no
  vars_files:
    - nginx-nodes-gce.yml
  pre_tasks:
    - name: print env variables
      shell: printenv
      register: print_env

    - debug:
        var: print_env.stdout

  #roles:
  #  - ansible-role-gce