- hosts: tag_role_nginx:&tag_app_nginx_standalone
  pre_tasks:
    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/7/x86_64/
        state: present
    - name: add www-data user
      user:
        name: www-data
        state: present

  roles:
    - jdauphant.ssl-certs
    - role: jdauphant.nginx
      nginx_configs:
        ssl:
          - ssl_certificate_key {{ssl_certs_privkey_path}}
          - ssl_certificate     {{ssl_certs_cert_path}}
      nginx_sites:
        default:
          - listen 443 ssl
          - server_name _
          - root "/usr/share/nginx/html"
          - index index.html

