---
- name: custom-service | Install script
  copy:
    src: customservice.sh
    dest: /root/
    mode: "u+rwx,g+x,o+x"

- name: custom-service | Create Unit file
  template: src=customservice.service.j2 dest=/lib/systemd/system/customservice.service mode=644
  notify:
    - reload systemctl

- name: custom-service | Start customservice
  service: name=customservice.service state=started enabled=yes