---
- name: Install epel
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install old version of perl
  yum:
    name: perl-5.16.3-286.el7
    state: present

- name: List packages
  yum:
    list=installed
  register: yum_packages

- name: Check perl version
  debug: var=item
  with_items: "{{ yum_packages|json_query(jsonquery) }}"
  vars:
    jsonquery: "results[?name=='perl']"

- name: Update perl
  yum:
    name: perl
    state: latest

- name: List packages
  yum:
    list=installed
  register: yum_packages

- name: Check perl version
  debug: var=item
  with_items: "{{ yum_packages|json_query(jsonquery) }}"
  vars:
    jsonquery: "results[?name=='perl']"


