---
- name: rest-api | List Ansible Tower users
  uri:
    url: https://{{ rest_url }}/api/v1/users/
    method: GET
    user: "{{ rest_username }}"
    password: "{{ rest_password }}"
    force_basic_auth: yes
    validate_certs: no
  register: restdata

- name: rest-api | Output rest data
  debug:
    msg: "{{ restdata.json }}"

- name: rest-api | Add a new Ansible Tower user
  uri:
    url: https://{{ rest_url }}/api/v1/users/
    method: POST
    user: "{{ rest_username }}"
    password: "{{ rest_password }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 201
    body_format: json
    headers:
      Content-Type: application/json
    body: >
      {
        "username": "demouser1",
        "password": "demo",
        "first_name": "demo",
        "last_name": "user1",
        "email": "demouser1@example.com"
      }
  register: restreturn
  when: not 'demouser1' in restdata.json.results | map(attribute='username') | list

- name: rest-api | Add a new user {{ demo_user_2.username }}
  uri:
    url: https://{{ rest_url }}/api/v1/users/
    method: POST
    user: "{{ rest_username }}"
    password: "{{ rest_password }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 201
    body_format: json
    headers:
      Content-Type: application/json
    body: "{{ item | to_json }}"
  register: restreturn2
  when: not item.username in restdata.json.results | map(attribute='username') | list
  with_items: "{{ demo_users }}"
